---
- name: Install nginx
  apt: 
    name: nginx 
    state: latest
    update_cache: true

- name: install letsencrypt
  apt: 
    name: letsencrypt
    state: latest
  when: whichcert == "letsencrypt"

- name: install apache2-utils
  apt:
    name: ['apache2-utils', 'python-passlib']
    state: latest
  
- name: Remove default nginx config
  file: 
    name: /etc/nginx/sites-enabled/default 
    state: absent

- name: configuring nginx
  copy: 
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf

- name: adding default proxy behaviour
  copy: 
    src: proxy.conf 
    dest: /etc/nginx/sites-available/proxy.conf

- name: Install nginx site for letsencrypt requests
  template:
    src: templates/nginx-http.j2
    dest: /etc/nginx/sites-enabled/http
  notify: restart nginx
  when: whichcert == "letsencrypt"

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/html -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  when: whichcert == "letsencrypt"

- name: previous task to generate self signed certificate
  file: 
    path: /etc/nginx/ssl
    state: directory
    mode: 0755
  when: whichcert != "letsencrypt"

- name: generating self signed certificated
  command: openssl req -new -nodes -x509 -subj "/CN={{ ov_public_hostname }}" -days 365 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -extensions v3_ca
  args:
    creates: /etc/nginx/ssl/nginx.crt
  when: whichcert == "selfsigned"

- name: copying user certificates
  copy: 
    src: "{{ item }}"
    dest: /etc/nginx/ssl
  with_items:
    - nginx.key
    - nginx.crt
  when: whichcert == "owncert"

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: adding entry for OpenVidu requests
  template:
    src: templates/kms-ov.conf.j2
    dest: /etc/nginx/sites-enabled/kms-ov

- name: Creating user for kibana
  htpasswd:
    path: /etc/nginx/conf.d/kibana.htpasswd
    name: "{{ KibanaUser }}"
    password: "{{ KibanaPassword }}"
    owner: root
    group: www-data
    mode: 0640

- name: adding default server
  template:
    src: templates/default.j2 
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: copying default index.html
  copy:
    src: index.html
    dest: /var/www/html

- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Certbot automatic renewal.
    job: "sudo /usr/bin/letsencrypt renew "
    minute: "0"
    hour: "0"
  when: whichcert == "letsencrypt"