---
- name: creating working dir
  file:
    path: "/opt/openvidu"
    state: "directory"
    mode: 0755

- name: installing Java 8
  apt:
    name: openjdk-8-jdk
    update_cache: yes

- name: installing Redis
  apt:
    name: redis-server
  notify: restart redis

- name: download helper
  copy:
    src: download_ov.sh
    dest: /usr/local/bin
    mode: u+rwx

- name: downloading release OpenVidu Server
  shell: /usr/local/bin/download_ov.sh {{ version }}

- name: copying openvidu launch script
  template:
    src: "openvidu-server.sh"
    dest: "/usr/local/bin"
    mode: "u+rwx"

- name: copying openvidu application.properties
  template:
    src: "application.properties.j2"
    dest: "/opt/openvidu/application.properties"
    mode: "u+rwx"

- name: copying script for aws signal
  template:
    src: "check_app_ready.sh"
    dest: "/usr/local/bin"
    mode: "0755"
  when: run_ec2

- name: creating recording directory
  file:
    path: /opt/openvidu/recordings
    state: directory
    mode: 0777