---
- name: copying the script to generate demos structure
  copy:
    src: "openvidu_create_demos_structure.sh"
    dest: "/usr/local/bin/openvidu_create_demos_structure.sh"
    mode: 0755

- name: creating demos structure
  shell: /usr/local/bin/openvidu_create_demos_structure.sh {{ ov_release }} {{ demos_release }} {{ ovc_release }}

- name: creating basic-webinar launcher
  template: 
    src: "app.sh-basic-webinar.j2"
    dest: "/var/www/html/basic-webinar/app.sh"
    mode: 0755

- name: creating classroom demo launcher
  template:
    src: "templates/app.sh.j2"
    dest: "/var/www/html/classroom/app.sh"
    mode: 0755


